export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'

export const UPDATE_APP_LIST = 'UPDATE_APP_LIST'
export const UPDATE_CURR_APP_SLIDE_INDEX = 'UPDATE_CURR_APP_SLIDE_INDEX'
